version: "3"

services:
        coupon-server:
                container_name: coupon-server
                image: sysu2019semcdfhlz/coupon-server
                ports:
                        - "3000:3000"
                depends_on:
                        - coupon-db
        
        coupon-db:
                container_name: coupon-db
                image: mongo:4.2.1-bionic
                command: mongod --replSet "rs0"

        coupon-db-slave1:
                container_name: coupon-db-slave1
                image: mongo:4.2.1-bionic
                command: mongod --replSet "rs0"
        coupon-db-slave2:
                container_name: coupon-db-slave2
                image: mongo:4.2.1-bionic
                command: mongod --replSet "rs0"
        coupon-db-slave3:
                container_name: coupon-db-slave3
                image: mongo:4.2.1-bionic
                command: mongod --replSet "rs0"
