name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag sysu2019semcdfhlz/coupon-rm:4node
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        docker push sysu2019semcdfhlz/coupon-rm:4node
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
